version: 2.1
jobs:
  unit-test-8:
    resource_class: large
    docker:
      - image: 'circleci/openjdk:8u222-stretch-node'
    environment:
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
      GRADLE_OPTS: -Dorg.gradle.jvmargs='-Xms6144m -Xmx6144m'
      _JAVA_OPTIONS: -XX:ActiveProcessorCount=4 -XX:ErrorFile=/home/circleci/artifacts/hs_err_pid%p.log -XX:HeapDumpPath=/home/circleci/artifacts
    steps:
      - checkout
      - run: ./gradlew clean
      - run: ./gradlew test
      - store_test_results: { path: ~/junit }
      - store_artifacts: { path: ~/artifacts }
  unit-test-11:
    resource_class: large
    docker:
      - image: 'circleci/openjdk:11-node'
    environment:
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
      GRADLE_OPTS: -Dorg.gradle.jvmargs='-Xms6144m -Xmx6144m'
      _JAVA_OPTIONS: -XX:ActiveProcessorCount=4 -XX:ErrorFile=/home/circleci/artifacts/hs_err_pid%p.log -XX:HeapDumpPath=/home/circleci/artifacts
    steps:
      - checkout
      - run: ./gradlew clean
      - run: ./gradlew test
      - store_test_results: { path: ~/junit }
      - store_artifacts: { path: ~/artifacts }
  publish:
    docker:
      - image: 'circleci/openjdk:8u222-stretch-node'
    environment:
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
      GRADLE_OPTS: -Dorg.gradle.jvmargs='-Xms6144m -Xmx6144m'
      _JAVA_OPTIONS: -XX:ActiveProcessorCount=2 -XX:ErrorFile=/home/circleci/artifacts/hs_err_pid%p.log -XX:HeapDumpPath=/home/circleci/artifacts
    steps:
      - checkout
      - attach_workspace: { at: /home/circleci }
      - deploy:
          command: ./gradlew --parallel --stacktrace --continue publish
      - store_test_results: { path: ~/junit }
      - store_artifacts: { path: ~/artifacts }
workflows:
  version: 2
  build:
    jobs:
      - unit-test-8:
          filters: { tags: { only: /.*/ } }
      - unit-test-11:
          filters: { tags: { only: /.*/ } }
